variables:
- group: DemoSemanticModel

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: run_testing_pipeline
  displayName: Run CAT tests
  jobs:
  - job: run_testing_pipeline

    steps:
      - task: PowerShell@2
        displayName: 'Install CAT'
        inputs:
          targetType: 'inline'
          workingDirectory: $(System.DefaultWorkingDirectory)
          pwsh: true # important! this tells the agent to use PowerShell 7
          script: |
              Install-Module CAT -AcceptLicense -Force -AllowClobber -Scope CurrentUser

      - task: PowerShell@2
        displayName: 'Execute tests'
        inputs:
          targetType: 'inline'
          workingDirectory: $(System.DefaultWorkingDirectory)
          pwsh: true # important! this tells the agent to use PowerShell 7
          script: |
              # Specify the file path
              $file = "$(System.DefaultWorkingDirectory)/tests/CATProject.cat.yaml"

              #Import CAT module to session
              Import-Module CAT

              #Set licence key
              Set-CatInstance -LicenseKey $licencekey

              # Run CAT project
              Invoke-CatProject -Path $file

        env:
          # Set the environment variable values here - using the Library variables
          Demo_Service_Principle_Application_ID: $(Demo_Service_Principle_Application_ID)
          Demo_Service_Principle_Secret: $(Demo_Service_Principle_Secret)