variables:
- group: DemoSemanticModel

trigger: none

pool:
  vmImage: ubuntu-latest

stages:
- stage: run_testing_pipeline
  displayName: Run CAT tests
  jobs:
  - job: run_testing_pipeline

    steps:
      - task: PowerShell@2
        displayName: 'Install CAT'
        inputs:
          targetType: 'inline'
          workingDirectory: $(System.DefaultWorkingDirectory)
          pwsh: true # important! this tells the agent to use PowerShell 7
          script: |
              Install-Module CAT -AcceptLicense -Force -AllowClobber -Scope CurrentUser
